name: Java CI with Gradle - Nightly

#on:
#  schedule:
#    - cron: '0 17 * * *'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get latest commit hash
        id: current
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get last published commit hash
        id: last
        run: |
          last_sha=$(curl -s "https://service.fpsmaster.top/api/github/latest/commit?branch=${GITHUB_REF}")
          echo "sha=$last_sha" >> $GITHUB_OUTPUT

      - name: Check if new commit exists
        id: check
        run: |
          if [ "${{ steps.current.outputs.sha }}" = "${{ steps.last.outputs.sha }}" ]; then
            echo "No new commit since last build. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "New commit detected. Continuing."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if no new commit
        if: steps.check.outputs.skip == 'true'
        run: exit 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.6'

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-libs
          path: build/libs/

